apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Comment out cert-manager annotations for development
    # cert-manager.io/cluster-issuer: "letsencrypt-dev"
    # # Force HTTPS by redirecting HTTP to HTTPS
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  # Specify the TLS settings for HTTPS
  # tls:
  # - hosts:
  #   - nineteen17dns.com
  #   secretName: my-tls-secret # Use the secret created with mkcert
  rules:
  - host: nineteen17dns.com
    http:
      paths:
      - path: /user-service(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service-svc
            port:
              number: 4000
      - path: /product-service(/|$)(.*)
        pathType: Prefix
        backend: 
          service:
            name: product-service-svc
            port:
              number: 4001
      - path: /order-service(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: order-service-svc
            port:
              number: 4002
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-svc
            port:
              number: 3000
