apiVersion: apps/v1
kind: Deployment
metadata:
 name: product-service
spec:
 replicas: 3  # Increase the number of replicas
 strategy:
   type: RollingUpdate  # Ensure RollingUpdate strategy is used
   rollingUpdate:
     maxUnavailable: 1  # Ensure at least one pod is always available
     maxSurge: 1
 selector:
   matchLabels:
     app: product-service
 template:
   metadata:
     labels:
       app: product-service
   spec:
     containers:
     - name: product-service
       image: nineteen17dh/product-service
       resources:
          limits:
            memory: 128Mi
            cpu: 500m
       ports:
       - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001