apiVersion: apps/v1
kind: Deployment
metadata:
 name: product-service
spec:
 replicas: 1
 selector:
   matchLabels:
     app: product-service
 template:
   metadata:
     labels:
       app: product-service
   spec:
     containers:
     - name: product-service
       image: nineteen17dh/product-service:latest
       resources:
          limits:
            memory: 128Mi
            cpu: 500m
       ports:
       - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001