apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: microservice-e-commerce-app
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: nineteen17dh/product-service
      context: app/product-service
      docker:
        dockerfile: Dockerfile
    - image: nineteen17dh/user-service
      context: app/user-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/dev/product-service-manifests.yaml
    - k8s/dev/user-service-manifests.yaml
    - k8s/dev/ingress.yaml
    - k8s/dev/rabbitmq.yaml