apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vite-base-url-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: vite-base-url
    creationPolicy: Owner
  data:
    - secretKey: VITE_BASE_URL
      remoteRef:
        key: VITE_BASE_URL
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vite-access-token-private-key-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: vite-access-token-private-key
    creationPolicy: Owner
  data:
    - secretKey: VITE_ACCESS_TOKEN_PRIVATE_KEY
      remoteRef:
        key: VITE_ACCESS_TOKEN_PRIVATE_KEY
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-mongo-uri-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: product-mongo-uri
    creationPolicy: Owner
  data:
    - secretKey: PRODUCT_MONGO_URI
      remoteRef:
        key: PRODUCT_MONGO_URI
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-mongo-uri-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: user-mongo-uri
    creationPolicy: Owner
  data:
    - secretKey: USER_MONGO_URI
      remoteRef:
        key: USER_MONGO_URI
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-mongo-uri-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: order-mongo-uri
    creationPolicy: Owner
  data:
    - secretKey: ORDER_MONGO_URI
      remoteRef:
        key: ORDER_MONGO_URI
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: access-token-private-key-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: access-token-private-key
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_TOKEN_PRIVATE_KEY
      remoteRef:
        key: ACCESS_TOKEN_PRIVATE_KEY
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: refresh-token-private-key-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: refresh-token-private-key
    creationPolicy: Owner
  data:
    - secretKey: REFRESH_TOKEN_PRIVATE_KEY
      remoteRef:
        key: REFRESH_TOKEN_PRIVATE_KEY
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amqp-url-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: amqp-url
    creationPolicy: Owner
  data:
    - secretKey: AMQP_URL
      remoteRef:
        key: AMQP_URL
        property: value
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-secret-key-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: stripe-secret-key
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: STRIPE_SECRET_KEY
        property: value
---
apiVersion: external-secrets.io.v1beta1
kind: ExternalSecret
metadata:
  name: stripe-webhook-secret-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: stripe-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: STRIPE_WEBHOOK_SECRET
        property: value
